[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate", "cd ../.. && pnpm install"]

[phases.build]
cmds = ["cd ../.. && pnpm --filter @repo/web build"]

[start]
cmd = "pnpm start"
