[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["corepack enable", "corepack prepare pnpm@latest --activate", "pnpm install"]

[phases.build]
cmds = ["pnpm --filter @repo/cms build"]

[start]
cmd = "cd apps/cms && pnpm start"
